[package]
name = "nesemu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"

[dependencies.lazy_static]
git = "https://github.com/Kimundi/lazy-static.rs"
